--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyAuctions
branches:
  - master
projects:
  PiggyAuctions:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version: ^0.5
      - src: muqsit/InvMenu/InvMenu
        version: ^3.1
      - src: poggit/libasynql/libasynql
        version: ^3.2.0
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: 1.0.1
    lint:
      phpstan: false
...