--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyAuctions
branches:
  - master
projects:
  PiggyAuctions:
    path: ""
    libs:
      - src: Paroxity/Commando/Commando
        version: ^2.1.2
      - src: muqsit/InvMenu/InvMenu
        version: ^4.1.1
      - src: poggit/libasynql/libasynql
        version: ^3.3.2
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3.0
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^2.0.0
    lint:
      phpstan: false
...