--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyAuctions
branches: 
  - master
projects:
  PiggyAuctions:
    path: ""
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.0.0
      - src: poggit/libasynql/libasynql
        version: ^3.4.0
      - src: muqsit/InvMenu/InvMenu
        version: ^4.4.1
      - src: DaPigGuy/FormAPI-4.0.0/libFormAPI
        version: ^2.1.0
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^3.0.1
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
    lint:
      phpstan: false
...
