name: PiggyAuctions
main: DaPigGuy\PiggyAuctions\PiggyAuctions
version: 1.0.6
api: 3.2.0
load: POSTWORLD
author: DaPigGuy
softdepend: ["EconomyAPI", "MultiEconomy"]
website: "https://github.com/DaPigGuy/PiggyAuctions/"
permissions:
  piggyauctions:
    default: op
    description: "Allow usage of all PiggyAuctions features"
    children:
      piggyauctions.command:
        default: op
        description: "Allow usage of all PiggyAuctions commands"
        children:
          piggyauctions.command.auctionhouse:
            default: true
            description: "Allow usage of the /auctionhouse command"
