database:
  # Options: sqlite, mysql
  type: sqlite
  sqlite:
    file: "auctions.sqlite"
  mysql:
    host: localhost
    username: root
    password: password
    schema: "piggyauctions"
  worker-limit: 1
economy:
  # Options: economyapi, multieconomy, xp
  provider: economyapi
auctions:
  bid-limit: 2147483647
  starting-bid-limit: 2147483647
  duration-limit: 1209600
